/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wbq_jpegpractice_NativeUtil */

#ifndef _Included_com_wbq_jpegpractice_NativeUtil
#define _Included_com_wbq_jpegpractice_NativeUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wbq_jpegpractice_NativeUtil
 * Method:    compressBitmap
 * Signature: (Landroid/graphics/Bitmap;III[BZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wbq_jpegpractice_NativeUtil_compressBitmap
  (JNIEnv *env, jclass jclazz, jobject jobj, jint w, jint h, jint quality, jbyteArray fileNameStr, jboolean optmize);
#ifdef __cplusplus
}
#endif
#endif
